# This is a basic workflow to help you get started with Actions

name: Merge upstream branches
on:
  workflow_dispatch:
#  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
#    - cron:  '* * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Pauldevt'
          git config --global user.email 'pauldevt@users.noreply.github.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/CVEProject/cvelist.git
          git fetch upstream
          
          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          
          git checkout -b master
          git merge --no-edit upstream/master
          git push origin master